package com.amazonaws.lambda.datamodel;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBIgnore;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName = "Announcement")
	public class Announcement {
	private String announcementName;
	private String id;
	private String announcementText;
	private String boardName;

	public Announcement() {

	}

	public Announcement(String id, String announcementName, String announcementText, String boardName) {
		this.announcementName = announcementName;
		this.id = id;
		this.announcementText = announcementText;
		this.boardName = boardName;
	}

	@DynamoDBAttribute(attributeName = "announcementName")
	public String getAnnouncementName() {
		return this.announcementName;
	}

	public void setAnnouncementName(String announcementName) {
		this.announcementName = announcementName;
	}

	@DynamoDBHashKey(attributeName = "id")
	@DynamoDBAutoGeneratedKey
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@DynamoDBAttribute(attributeName = "announcementText")
	public String getAnnouncementText() {
		return this.announcementText;
	}

	public void setAnnouncementText(String announcementText) {
		this.announcementText = announcementText;
	}

	@DynamoDBAttribute(attributeName = "boardName")
	public String getBoardName() {
		return this.boardName;
	}

	public void setBoardName(String boardName) {
		this.boardName = boardName;
	}

	@DynamoDBIgnore
	@Override
	public String toString() {
		return "id=" + getId() + ", announcementName=" + getAnnouncementName() + ", announcementText="
				+ getAnnouncementText() + ", boardName=" + getBoardName();
	}

}