package com.amazonaws.lambda.datamodel;

 

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBIgnore;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

 

@DynamoDBTable(tableName="Board")

 

public class Board {

 

    private String boardName;
    private String id;
    private String courseName;

 

    public Board() {

 

    }

 

    public Board(String id, String boardName,  String courseName) {
        this.boardName = boardName;
        this.id = id;
        this.courseName = courseName;
    }

 

    @DynamoDBAttribute(attributeName="boardName")
    public String getBoardName() {
        return this.boardName;
    }

 

    public void setBoardName(String boardName) {
        this.boardName = boardName;
    }

 

    @DynamoDBHashKey(attributeName="id")
    @DynamoDBAutoGeneratedKey
    public String getId() {
        return this.id;
    }

 

    public void setId(String id) {
        this.id = id;
    }

 

    @DynamoDBAttribute(attributeName="courseName")
    public String getCourseName() {
        return courseName;
    }

 

    public void setCourseName(String courseName) {
        this.courseName = courseName;
    }

 

    @DynamoDBIgnore
    @Override
    public String toString() { 
        return "id=" + getId() + ", boardName=" + getBoardName()
        + ", CourseName=" + getCourseName();
    }

 

}
 