package com.amazonaws.lambda.datamodel;

import java.util.List;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName = "Course")

public class Course {

	private String courseName;
	private String id;
	private String boardName;
	private List<String> registeredStudents;
	private String professorId;
	private String studentTA;
	private String department;
	private String notificationTopic;

	public Course() {

	}

	public Course(String id, String courseName, String boardName, List<String> registeredStudents, String professorId,
			String studentTA, String department) {
		this.courseName = courseName;
		this.id = id;
		this.boardName = boardName;
		this.registeredStudents = registeredStudents;
		this.professorId = professorId;
		this.studentTA = studentTA;
		this.department = department;
	}

	@DynamoDBAttribute(attributeName = "courseName")
	public String getcourseName() {
		return this.courseName;
	}

	public void setcourseName(String courseName) {
		this.courseName = courseName;
	}

	@DynamoDBHashKey(attributeName = "id")
	@DynamoDBAutoGeneratedKey
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@DynamoDBAttribute(attributeName = "boardName")
	public String getBoardName() {
		return this.boardName;
	}

	public void setBoardName(String boardName) {
		this.boardName = boardName;
	}

	@DynamoDBAttribute(attributeName = "registeredStudents")
	public List<String> getRegisteredStudents() {
		return this.registeredStudents;
	}

	public void setRegisteredStudents(List<String> registeredStudents) {
		this.registeredStudents = registeredStudents;
	}

	@DynamoDBAttribute(attributeName = "professorId")
	public String getProfessorId() {
		return this.professorId;
	}

	public void setProfessorId(String professorId) {
		this.professorId = professorId;
	}

	@DynamoDBAttribute(attributeName = "studentTA")
	public String getStudentTA() {
		return this.studentTA;
	}

	public void setStudentTA(String studentTA) {
		this.studentTA = studentTA;
	}

	@DynamoDBAttribute(attributeName = "department")
	public String getDepartment() {
		return this.department;
	}

	public void setDepartment(String department) {
		this.department = department;
	}

	@DynamoDBAttribute(attributeName = "notificationTopic")

	public String getNotificationTopic() {
		return notificationTopic;
	}

	public void setNotificationTopic(String notificationTopic) {
		this.notificationTopic = notificationTopic;
	}

}
