package com.amazonaws.lambda.datamodel;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBIgnore;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName = "Registrar")

	public class Registrar {
	
	private String registrationId;
	private String OfferingId;
	private String OfferingType;
	private int PerUnitPrice;
	private String department;

	public Registrar() {

	}

	public Registrar(String registrationId, String offeringId, String offeringType, int perUnitPrice,
			String department) {
		this.registrationId = registrationId;
		OfferingId = offeringId;
		OfferingType = offeringType;
		PerUnitPrice = perUnitPrice;
		this.department = department;
	}

	@DynamoDBHashKey(attributeName = "registrationId")
	@DynamoDBAutoGeneratedKey

	public String getRegistrationId() {
		return registrationId;
	}

	public void setRegistrationId(String registrationId) {
		this.registrationId = registrationId;
	}

	@DynamoDBAttribute(attributeName = "offeringId")
	public String getOfferingId() {
		return OfferingId;
	}

	public void setOfferingId(String offeringId) {
		OfferingId = offeringId;
	}

	@DynamoDBAttribute(attributeName = "offeringType")
	public String getOfferingType() {
		return OfferingType;
	}

	public void setOfferingType(String offeringType) {
		OfferingType = offeringType;
	}

	@DynamoDBAttribute(attributeName = "perUnitPrice")
	public int getPerUnitPrice() {
		return PerUnitPrice;
	}

	public void setPerUnitPrice(int perUnitPrice) {
		PerUnitPrice = perUnitPrice;
	}

	@DynamoDBAttribute(attributeName = "department")
	public String getDepartment() {
		return department;
	}

	public void setDepartment(String department) {
		this.department = department;
	}

}