package com.csye6225.spring2020.courseservice.datamodel;

import java.util.Date;
import java.util.HashMap;
import java.util.Map;

import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlTransient;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBIgnore;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBIndexHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

public class Course {
	private long courseId;
	private long profId;
	private String courseName;
	private long programId;
	private String startDate;
	private String endDate;
	private String courseMaterial;
	private long studentTA;

	public long getStudentTA() {
		return studentTA;
	}

	public void setStudentTA(long studentTA) {
		this.studentTA = studentTA;
	}

	public long getProfId() {
		return profId;
	}

	public void setProfId(long profId) {
		this.profId = profId;
	}

	public long getProgramId() {
		return programId;
	}

	public void setProgramId(long programId) {
		this.programId = programId;
	}

	public String getCourseMaterial() {
		return courseMaterial;
	}

	public void setCourseMaterial(String courseMaterial) {
		this.courseMaterial = courseMaterial;
	}

	public Course() {

	}

	public Course(long courseId, String courseName, long profId, long programId, String startDate, String endDate,
			String courseMaterial, long studentTA) {
		this.courseId = courseId;
		this.profId = profId;
		this.courseName = courseName;
		this.programId = programId;
		this.startDate = startDate;
		this.endDate = endDate;
		this.courseMaterial = courseMaterial;
		this.studentTA = studentTA;
	}

	public long getCourseId() {
		return courseId;
	}

	public void setCourseId(long courseId) {
		this.courseId = courseId;
	}

	public String getCourseName() {
		return courseName;
	}

	public void setCourseName(String courseName) {
		this.courseName = courseName;
	}

	public String getStartDate() {
		return startDate;
	}

	public void setStartDate(String startDate) {
		this.startDate = startDate;
	}

	public String getEndDate() {
		return endDate;
	}

	public void setEndDate(String endDate) {
		this.endDate = endDate;
	}

	@Override
	public String toString() {
		return "Course [courseId=" + courseId + ", profId=" + profId + ", courseName=" + courseName + ", programId="
				+ programId + ", startDate=" + startDate + ", studentTA= " + studentTA + ", endDate=" + endDate
				+ ", courseMaterial=" + courseMaterial + "]";
	}

}
