package com.csye6225.spring2020.courseserviceDynamo.datamodel;

import java.util.Date;
import java.util.HashMap;
import java.util.Map;

import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlTransient;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBIgnore;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBIndexHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName="Courses")
public class Course {
	private long courseId;
	private long profId;
	private String courseName;
	private long programId;
	private String startDate;
	private String endDate;
	private long TAId;
	private String courseMaterial;

	

	public Course() {

	}

	public Course(long courseId, String courseName, long profId, long programId, String startDate, String endDate, long TAId,String courseMaterial) {
		this.courseId = courseId;
		this.profId = profId;
		this.courseName = courseName;
		this.programId = programId;
		this.startDate = startDate;
		this.endDate = endDate;
		this.TAId = TAId;
		this.courseMaterial = courseMaterial;
	}
	
	@DynamoDBAttribute(attributeName="TAId")
	public long getTAId() {
		return TAId;
	}

	public void setTAId(long TAId) {
		this.TAId = TAId;
	}

	@DynamoDBAttribute(attributeName="ProfId")
	public long getProfId() {
		return profId;
	}

	public void setProfId(long profId) {
		this.profId = profId;
	}

	@DynamoDBAttribute(attributeName="ProgramId")
	public long getProgramId() {
		return programId;
	}

	public void setProgramId(long programId) {
		this.programId = programId;
	}
	
	
	@DynamoDBHashKey(attributeName="CourseId")
	public long getCourseId() {
		return courseId;
	}

	public void setCourseId(long courseId) {
		this.courseId = courseId;
	}

	@DynamoDBAttribute(attributeName="CourseName")
	public String getCourseName() {
		return courseName;
	}

	public void setCourseName(String courseName) {
		this.courseName = courseName;
	}

	@DynamoDBAttribute(attributeName="StartDate")
	public String getStartDate() {
		return startDate;
	}

	public void setStartDate(String startDate) {
		this.startDate = startDate;
	}

	@DynamoDBAttribute(attributeName="EndDate")
	public String getEndDate() {
		return endDate;
	}

	public void setEndDate(String endDate) {
		this.endDate = endDate;
	}
	
	@DynamoDBAttribute(attributeName="CourseMaterial")
	public String getCourseMaterial() {
		return courseMaterial;
	}

	public void setCourseMaterial(String courseMaterial) {
		this.courseMaterial = courseMaterial;
	}

	@Override
	public String toString() {
		return "Course [courseId=" + courseId + ", profId=" + profId + ", courseName=" + courseName + ", programId="
				+ programId + ", startDate=" + startDate + ", TAId= " + TAId + ", endDate=" + endDate + ", courseMaterial=" + courseMaterial
				+ "]";
	}

}
